name: '@volta-cli/action'
description: 'Setup a Node.js environment with Volta'
author: 'Robert Jackson <me@rwjblue.com>'
inputs:
  volta-version:
    description: 'Version Spec of the volta version to use.  Examples: 0.6.x, 10.15.1, >=10.15.0'
    default: ''
  node-version:
    description: 'Version Spec of the node version to use.  Examples: 10.6.x, 10.15.1, >=10.15.0'
    default: ''
  npm-version:
    description: 'Version Spec of the npm version to use.  Examples: 7.5.x, 7.5.3, >=7.5.3'
    default: ''
  yarn-version:
    description: 'Version Spec of the yarn version to use.  Examples: 1.6.x, 10.15.1, >=10.15.0'
    default: ''
  registry-url:
    description: 'Optional registry to set up for auth. Will set the registry in a project level .npmrc file, and set up auth to read in from env.NODE_AUTH_TOKEN'
  always-auth:
    description: 'Set always-auth in npmrc'
    default: 'false'
branding:
  icon: 'zap'
  color: 'yellow'
runs:
  using: 'node12'
  main: 'dist/index.js'
